### ISSUE TITLE
Allow the configuration of filters performance / flexibility trade-off

### ISSUE THREAD

**Issue by andrehp** [topfreegames/offers#16]
In the current state querying numbers by interval is far less efficient than filtering by strings, this is due to the GIN index on the filters column, which is not used by interval queries.

Allowing offers with empty values for a given filter attribute also impact the query performance significantly, this is due to the fact that the query with this condition cannot make use of the GIN index.

The trade-off is heavily based on the number of offers a game has, and if it has only a few offers the query performance will not be significantly different, but for a larger amount (thousands of offers for a game) using interval filters is not efficient.

So I think that a solution to keep the filters' flexibility is to create options to specify if a query or game only allows efficient queries or if inefficient queries are allowed for the game. This configuration might be contained in the metadata field or even sent in the query string for GET available-offers.

**Comment by cscatolini** [comment]
Closed by 22db286.
