### ISSUE TITLE
NextAt returned in view and claim offer should check if offers is disabled.

### ISSUE THREAD

**Issue by cscatolini** [topfreegames/offers#9]
Even if the offer is disabled, when we receive a request viewing or claiming the offer we return a non-zero nextAt so the client still thinks the offer is enabled.

**Comment by andrehp** [comment]
Looking at the impression route it seems we will need to do a JOIN of offer_instance with offer to check if the offer is enabled.

I guess we just need to define if disabling an offer is a common ocurrence to justify this extra penalty
